# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.__config__)

1.21.6
<module 'numpy.__config__' from '/usr/local/lib/python3.7/dist-packages/numpy/__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(null_vector.size*null_vector.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info('add')

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
ten_fortynine_vector = np.arange(10,50)
print(ten_fortynine_vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
rev_ten_fortynine_vector = ten_fortynine_vector[::-1]
print(rev_ten_fortynine_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
nine_ele_vec = np.arange(9)
tbt_nine_ele_vec = nine_ele_vec.reshape(3,3)
print(tbt_nine_ele_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
array10 = np.array([1,2,0,0,4,0])
print(array10.nonzero())

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
id_matx = np.eye(3)
print(id_matx)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
tbtone_rand = np.random.random(27)
tbt_rand = tbtone_rand.reshape(3,3,3)
print(tbt_rand)

[[[0.90806151 0.92166164 0.10164823]
  [0.88360814 0.95631543 0.12816601]
  [0.06579032 0.30748062 0.45717447]]

 [[0.99416129 0.82649025 0.72713329]
  [0.95666255 0.65683915 0.30847234]
  [0.15384824 0.35834203 0.74975951]]

 [[0.94655246 0.03190553 0.04262514]
  [0.95210923 0.48890198 0.85163063]
  [0.46408231 0.90191247 0.16700606]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
onetbt_mat = np.random.random(100)
tbt_mat = onetbt_mat.reshape(10,10)
print(tbt_mat.min())
print(tbt_mat.max())

0.01883651616519333
0.9854670500465363


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
thirty_vec = np.random.random(30)
print(thirty_vec.mean())

0.48494330360973875


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
ftarray = np.ones(25).reshape(5,5)
ftarray[1:-1,1:-1] = 0
print(ftarray)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
starray = np.random.randint(low = 0, high = 9, size = 25).reshape(5,5)
pad_array = np.pad(starray,(1,1),'constant',constant_values=(0, 0))
print(pad_array)

[[0 0 0 0 0 0 0]
 [0 1 8 2 2 8 0]
 [0 5 4 1 8 0 0]
 [0 6 8 4 4 6 0]
 [0 0 4 5 7 1 0]
 [0 7 3 5 2 8 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
fbf = np.diag(1+np.arange(4),k=-1)
print(fbf)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
ebe = np.zeros(64).reshape(8,8)
ebe[1::2,::2] = 1
ebe[::2,1::2] = 1
print(ebe)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
oz = [[0,1],[1,0]]
oztile = np.tile(oz,(4,4))
print(oztile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
fbf = np.random.randint(low=1,high=9,size=25).reshape(5,5)
normfbf = (fbf-fbf.min())/(fbf.max()-fbf.min())
print(normfbf)

[[0.57142857 0.         1.         0.42857143 0.28571429]
 [0.14285714 0.85714286 0.28571429 0.57142857 0.14285714]
 [0.14285714 0.28571429 1.         0.85714286 0.42857143]
 [0.57142857 0.57142857 0.         0.         0.14285714]
 [0.28571429 0.42857143 0.14285714 1.         0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['green'])
type(color)

2


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
amat = np.random.randint(low=0,high=9,size=15).reshape(5,3)
bmat = np.random.randint(low=0,high=9,size=6).reshape(3,2)
pdtmat = amat.dot(bmat)
print(pdtmat)

[[88 49]
 [64 27]
 [44 21]
 [76 42]
 [68 24]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
onemat = np.arange(10)
print(onemat)
onemat[(onemat>2) & (onemat<9)] = -1*onemat[(onemat>2) & (onemat<9)]
print(onemat)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(5)
print(z)

[0 1 2 3 4]


In [ ]:
z**z #legal

array([  1,   1,   4,  27, 256])

In [ ]:
z <- z #legal

array([False, False, False, False, False])

In [ ]:
1j*z #legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [ ]:
z/1/1 #legal

array([0., 1., 2., 3., 4.])

In [ ]:
z<z>z #not legal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
tnarr = np.random.random(5)
print(tnarr)
tnarr = np.round(tnarr,1)
print(tnarr) 

[0.23547004 0.00620748 0.78482887 0.39911518 0.05843047]
[0.2 0.  0.8 0.4 0.1]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
tarr1 = np.random.randint(low=1,high=15,size=10)
tarr2 = np.random.randint(low=1,high=15,size=10)
np.intersect1d(tarr1,tarr2)

array([11, 13])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all='ignore')
np.errstate(divide='ignore')

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1)) #imaginary number not in numpy by default

nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [ ]:
np.emath.sqrt(-1) #use emath for handling imaginary numbers

1j

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1) #false

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print(np.datetime64('today'))
print(np.datetime64('today') - np.timedelta64(1,'D')) # 'D' is for forcing Date unit
print(np.datetime64('today') + np.timedelta64(1,'D'))

2022-08-18
2022-08-17
2022-08-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
days = np.arange('2016-07','2016-08', dtype='datetime64[D]')
print(days)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.arange(10)/2
B = np.arange(10)/2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=B)
print(B)

[ -0.    -0.25  -1.    -2.25  -4.    -6.25  -9.   -12.25 -16.   -20.25]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
tsarr = np.random.randn(10)
print(np.floor(tsarr))
print(np.ceil(tsarr))
print(np.trunc(tsarr))

[-1.  0. -1. -1. -1. -1. -1. -1. -2. -2.]
[-0.  1. -0. -0. -0. -0. -0. -0. -1. -1.]
[-0.  0. -0. -0. -0. -0. -0. -0. -1. -1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
tsar = np.random.randint(low=0,high=4,size=25).reshape(5,5)
print(tsar)

[[0 0 0 3 3]
 [2 1 1 3 2]
 [1 0 0 3 3]
 [3 3 1 3 2]
 [3 2 3 2 1]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
iter = (a for a in range(10))
te = np.fromiter(iter,dtype=int)
print(te)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
tn = np.linspace(0.1,1,num=10,endpoint=False)
print(tn)

[0.1  0.19 0.28 0.37 0.46 0.55 0.64 0.73 0.82 0.91]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
fo = np.random.random(10)
fo = np.sort(fo)
print(fo)

[0.13595051 0.1607565  0.23982149 0.4411362  0.502957   0.53896756
 0.60997082 0.64804917 0.70902495 0.91649622]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
f1 = np.arange(5)
sum = np.add.reduce(f1)
print(sum)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
f21 = np.random.random(5)
f22 = np.random.random(5)
print(np.array_equal(f21,f22))
print(np.allclose(f21,f22,rtol=0.1,atol=0.1))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
ftr = np.arange(5)
print(ftr)
ftr[2] = 9
print(ftr)
ftr.setflags(write=False)
#ftr[1] = 8
print(ftr)

[0 1 2 3 4]
[0 1 9 3 4]
[0 1 9 3 4]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z = np.random.randint(1,9,(10,2))
x = z[:,0]
y = z[:,1]
pL = np.sqrt(x**2+y**2)
pA = np.arctan2(y,x)
polar = np.c_[pL,pA]
print(polar)

[[7.81024968 0.69473828]
 [8.06225775 0.51914611]
 [4.12310563 0.24497866]
 [7.07106781 0.14189705]
 [5.83095189 0.5404195 ]
 [9.21954446 0.86217005]
 [8.60232527 0.95054684]
 [7.61577311 0.40489179]
 [8.54400375 1.21202566]
 [4.47213595 1.10714872]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
ff = np.random.randint(1,20,10)
print(ff)
ff[ff.argmax()] = 0
print(ff)

[14  3  9 19 15  2 10  1  5 18]
[14  3  9  0 15  2 10  1  5 18]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.linspace(0,10,5)
y = np.linspace(0,10,5)
xymesh = np.meshgrid(x,y)
#print(x)
print(xymesh)

[array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ]]), array([[ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 5. ,  5. ,  5. ,  5. ,  5. ],
       [ 7.5,  7.5,  7.5,  7.5,  7.5],
       [10. , 10. , 10. , 10. , 10. ]])]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.linspace(6,11,5)
y = np.linspace(0,5,5)
xmy = np.subtract.outer(x,y)
cxy = 1/xmy
print(cxy)

[[0.16666667 0.21052632 0.28571429 0.44444444 1.        ]
 [0.13793103 0.16666667 0.21052632 0.28571429 0.44444444]
 [0.11764706 0.13793103 0.16666667 0.21052632 0.28571429]
 [0.1025641  0.11764706 0.13793103 0.16666667 0.21052632]
 [0.09090909 0.1025641  0.11764706 0.13793103 0.16666667]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64, ]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=sys.maxsize)
x = np.randn(5)
print(x)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
myarray = np.random.uniform(0,5,5)
scalar = 2
diffarr = np.abs(myarray - scalar)
leastdiff = diffarr.argmin()
print(myarray)
print(myarray[leastdiff])

[3.31932652 1.71948771 2.27569977 4.98135901 4.48844889]
2.275699773673901


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
z = np.ones(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(z)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         1.1648727  0.88343955 1.11078912 0.82066678 0.71367366
  0.69651689 0.52133097 0.89664619 0.92252211]
 [1.1648727  0.         0.28144846 0.05834856 0.34869333 0.48243651
  0.74316377 0.64922866 0.29391335 0.26913229]
 [0.88343955 0.28144846 0.         0.22840546 0.07788048 0.22419506
  0.53814829 0.37012837 0.10802849 0.10673022]
 [1.11078912 0.05834856 0.22840546 0.         0.29912198 0.43759686
  0.6864774  0.59349426 0.23556774 0.23093577]
 [0.82066678 0.34869333 0.07788048 0.29912198 0.         0.14633284
  0.53944101 0.31862775 0.16783953 0.11287927]
 [0.71367366 0.48243651 0.22419506 0.43759686 0.14633284 0.
  0.57500692 0.26404127 0.30435471 0.21744212]
 [0.69651689 0.74316377 0.53814829 0.6864774  0.53944101 0.57500692
  0.         0.36711131 0.46283879 0.63965926]
 [0.52133097 0.64922866 0.37012837 0.59349426 0.31862775 0.26404127
  0.36711131 0.         0.37535083 0.42986284]
 [0.89664619 0.29391335 0.10802849 0.23556774 0.16783953 0.30435471
  0.46283879 0.37535

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.int32, copy=False)
print(Z)
print(Z_1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [3]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [6]:
ff = np.arange(5,10)
# np.ndenumerate is equivalent of enumerate in numpy
for i,e in np.ndenumerate(ff):
  print(i,e)
# np.ndindex gives the indices for a given shape of array
for i in np.ndindex(2,2):
  print(i)

(0,) 5
(1,) 6
(2,) 7
(3,) 8
(4,) 9
(0, 0)
(0, 1)
(1, 0)
(1, 1)


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [7]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [19]:
n = 10
p = 8
Z = np.zeros((n,n))
print('Original Matrix \n',Z)
np.put(Z, np.random.choice(range(n*n), p, replace=True),1)
print('New Matrix \n',Z)

Original Matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
New Matrix 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [24]:
fe = np.random.randint(1,9,25).reshape(5,5)
print(fe)
fe = fe-fe.mean(axis=0)
print(fe)

[[8 8 6 8 4]
 [8 3 7 6 3]
 [7 7 1 4 7]
 [5 2 2 2 3]
 [3 8 6 1 6]]
[[ 1.8  2.4  1.6  3.8 -0.6]
 [ 1.8 -2.6  2.6  1.8 -1.6]
 [ 0.8  1.4 -3.4 -0.2  2.4]
 [-1.2 -3.6 -2.4 -2.2 -1.6]
 [-3.2  2.4  1.6 -3.2  1.4]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [36]:
fn = np.random.randint(0,9,(3,3))
print(fn)
fns = np.argsort(fn,axis=-1)
print(fns)

[[2 0 5]
 [5 0 3]
 [5 3 3]]
[[1 0 2]
 [1 2 0]
 [1 2 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [46]:
sy = np.random.randint(0,2,(3,3))
print(sy)
if False in sy.any(axis=0):
  print('Yes, Null column present')
else:
  print('No Null column present')

[[0 1 1]
 [1 0 1]
 [1 1 0]]
No Null column present


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [50]:
so_array = np.random.uniform(0,10,10)
print(so_array)
giv_value = 2
diff_array = abs(so_array-giv_value)
so_array[diff_array.argmin()]

[1.9309103  8.96145573 2.19534119 4.22232095 1.10686846 4.38953403
 1.56988959 0.99564485 9.0217198  2.14026871]


1.9309103041088937

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [74]:
starr1 = np.random.randint(1,9,(1,3))
starr2 = np.random.randint(1,9,(3,1))
sumv = []
print(starr1)
print(starr2)
for i,e in np.nditer((starr1,starr2)):
  sumv.append(i+e)
print(sumv)

[[7 4 3]]
[[1]
 [7]
 [2]]
[8, 5, 4, 14, 11, 10, 9, 6, 5]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [6]:
class A:
  def __init__(self):
    self.name = np.array(['Adam','Bob','Clarke','Dave'])
Aobj = A()
print(Aobj.name)

['Adam' 'Bob' 'Clarke' 'Dave']


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [12]:
Z = np.zeros(10)
I = np.random.randint(0,len(Z),20)
#print(I)
Z += np.bincount(I)
print(Z)

[1. 3. 1. 4. 2. 4. 1. 1. 2. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [13]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [14]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [15]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[72 41 45 34]
 [58 51 58 62]
 [48 60 41 62]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [16]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.4925154  0.48968662 0.46337905 0.4915801  0.55400701 0.41481324
 0.44332136 0.32751033 0.44919117 0.62362731]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [20]:
arr1 = np.random.randint(1,5,5)
arr2 = np.random.randint(1,5,5).reshape(5,1)
arr3 = np.dot(arr1,arr2)
print(np.diag(arr3))

[[28]]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [21]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [22]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [30]:
A = np.arange(25).reshape(5,5)
A[[0,1,2]] = A[[2,1,0]] # swap 1st and 3rd row
print(A)

[[10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [31]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 10) ( 1, 33) ( 1, 58) ( 1, 59) ( 6, 21) ( 6, 23) ( 7, 35) ( 7, 72)
 (10, 58) (10, 77) (10, 83) (13, 19) (13, 99) (19, 99) (21, 23) (27, 38)
 (27, 86) (33, 59) (35, 72) (36, 49) (36, 88) (38, 86) (39, 53) (39, 81)
 (40, 52) (40, 59) (49, 88) (52, 59) (53, 81) (77, 83)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [32]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [33]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [34]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [37]:
Z = np.random.randint(0,2,10)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-10,10,4)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[0 1 1 1 1 0 1 1 1 1]
Negating a boolean: 
[1 0 0 0 0 1 0 0 0 0]
original: 
[ 2.72671684  2.91387844  9.49527202 -3.38092498]
Change the sign of float inplace: 
[-2.72671684 -2.91387844 -9.49527202  3.38092498]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [38]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.4919108   3.73019581  4.24560978  2.51198934  5.75053076  6.30265805
  1.37204361 10.13772302  2.09513651  7.84134305]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [39]:
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 6.44093323  5.42340094  6.59271038 10.47829968  3.3527949 ]
 [ 3.12682842  8.461388    0.35153205  6.44781258  9.70641039]
 [ 2.93047449  0.51232048  7.37328556  7.41484265  0.03836739]
 [ 7.18515786  8.91845988  3.9711575  10.76375868  7.08756298]
 [ 9.49250335 10.59644968  5.00942628 13.00721298  7.35089932]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [40]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 5 6 4 7 8 2 5 1]
 [5 3 3 1 8 3 1 1 4 0]
 [1 5 1 7 5 2 1 4 3 7]
 [3 2 4 9 7 4 5 4 4 0]
 [3 1 5 9 2 4 2 3 0 1]
 [5 0 7 3 4 4 8 3 3 1]
 [7 7 6 8 7 3 0 2 7 5]
 [9 5 3 5 9 6 1 5 6 9]
 [6 8 6 7 2 3 3 3 8 4]
 [8 9 2 2 9 3 1 6 1 0]]
[[0 0 0 0 0]
 [0 7 2 5 6]
 [0 5 3 3 1]
 [0 1 5 1 7]
 [0 3 2 4 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [41]:
Z = np.arange(1,15,dtype=int)

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
print ('original: ')
print (Z)
print ('after strides: ')
print(R)

original: 
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
after strides: 
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [42]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [43]:
et = np.random.randint(1,5,10)
print(et)
etbin = np.bincount(et)
print(np.argmax(etbin))

[1 3 4 2 4 2 2 4 1 4]
4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [45]:
arra1 = np.random.randint(0,5,(10,10))
print("Original arrays:")
print(arra1)
n = 3
i = 1 + (arra1.shape[0]-3)
j = 1 + (arra1.shape[1]-3)
result = np.lib.stride_tricks.as_strided(arra1, shape=(i, j, n, n), strides = arra1.strides + arra1.strides)
print("\nContiguous 3x3 blocks:")
print(result)

Original arrays:
[[1 2 0 3 4 1 1 4 2 3]
 [1 3 0 4 2 0 2 0 4 2]
 [3 2 4 4 1 2 0 2 0 0]
 [4 1 0 1 4 2 4 4 2 0]
 [3 1 4 4 2 2 0 1 3 1]
 [4 3 3 4 4 1 2 2 1 2]
 [1 2 3 2 1 3 2 1 0 0]
 [0 1 3 4 0 4 1 0 1 1]
 [4 4 0 4 2 3 3 2 0 2]
 [0 4 1 2 0 1 1 1 3 3]]

Contiguous 3x3 blocks:
[[[[1 2 0]
   [1 3 0]
   [3 2 4]]

  [[2 0 3]
   [3 0 4]
   [2 4 4]]

  [[0 3 4]
   [0 4 2]
   [4 4 1]]

  [[3 4 1]
   [4 2 0]
   [4 1 2]]

  [[4 1 1]
   [2 0 2]
   [1 2 0]]

  [[1 1 4]
   [0 2 0]
   [2 0 2]]

  [[1 4 2]
   [2 0 4]
   [0 2 0]]

  [[4 2 3]
   [0 4 2]
   [2 0 0]]]


 [[[1 3 0]
   [3 2 4]
   [4 1 0]]

  [[3 0 4]
   [2 4 4]
   [1 0 1]]

  [[0 4 2]
   [4 4 1]
   [0 1 4]]

  [[4 2 0]
   [4 1 2]
   [1 4 2]]

  [[2 0 2]
   [1 2 0]
   [4 2 4]]

  [[0 2 0]
   [2 0 2]
   [2 4 4]]

  [[2 0 4]
   [0 2 0]
   [4 4 2]]

  [[0 4 2]
   [2 0 0]
   [4 2 0]]]


 [[[3 2 4]
   [4 1 0]
   [3 1 4]]

  [[2 4 4]
   [1 0 1]
   [1 4 4]]

  [[4 4 1]
   [0 1 4]
   [4 4 2]]

  [[4 1 2]
   [1 4 2]
   [4 2 2]]

  [[1 2 0]
   [4 2 4]
  

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [47]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [48]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print ('input array')
print (Z)
print ('block sum')
print (S)

input array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
block sum
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [49]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [50]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[99 98 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [51]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [52]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [54]:
x = np.random.rand(5)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.08 µs ± 55.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.04 µs ± 6.13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.15 µs ± 93.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [55]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [56]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[3 0 3]
 [4 0 0]
 [0 3 0]
 [0 0 0]
 [2 4 3]
 [0 1 2]
 [3 0 2]
 [3 1 1]
 [0 0 1]
 [1 0 2]]
[[3 0 3]
 [4 0 0]
 [0 3 0]
 [2 4 3]
 [0 1 2]
 [3 0 2]
 [3 1 1]
 [0 0 1]
 [1 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [57]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [58]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [64]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)